### ISSUE TITLE
initscripts fail after editing config files

### ISSUE THREAD

**Issue by IvanSanchez** [matrix-org/package-synapse-debian#1]
I have been running into several problems when trying to install `matrix-synapse` in my debian machines. 

After a lenghy chat with @erikj:jki.re, (starting at message `$1449586508271757TqgsC:matrix.org`), I discovered that the init scripts (i.e. `service matrix-synapse start`, `service matrix-synapse stop`, `restart`, etc) fail to run properly after I've edited the config files.

In order to reproduce the bug:
- Use a text editor that leaves a `*~` backup file after editing a file (yes, I use [Joe](https://en.wikipedia.org/wiki/Joe%27s_Own_Editor), call me weird)
- Edit some config file, so that the `/etc/matrix-synapse/conf.d/webclient.yaml~` file is created. Note the `~` at the end.
- Run `tail /var/log/syslog`. The log will contain something similar to:

```
systemd[1]: Starting LSB: <Enter a short description of the software>...
matrix-synapse[31910]: Found file in config directory that does not end in '.yaml': '/etc/matrix-synapse/conf.d/webclient.yaml~'. IGNORING.
matrix-synapse[31910]: touch: cannot run `touch' to «'/etc/matrix-synapse/conf.d/webclient.yaml~'.»: No such file or directory
matrix-synapse[31910]: chown: cannot access «'/etc/matrix-synapse/conf.d/webclient.yaml~'.»: No such file or directory     
```

After this point, I'm not sure what's going on. My guess is that the exit status of the init script is not handled properly. The behaviour is different if I edit a config file after or before shutting down synapse.

**Comment by richvdh** [comment]
> matrix-synapse[31910]: touch: cannot run `touch' to «'/etc/matrix-synapse/conf.d/webclient.yaml~'.»: No such file or directory
> matrix-synapse[31910]: chown: cannot access «'/etc/matrix-synapse/conf.d/webclient.yaml~'.»: No such file or directory     

AFAICT, the only file that gets `touch`ed and `chown`ed in this way should be the pid file, so this suggests that somehow it decided that the pid file was called `'/etc/matrix-synapse/conf.d/webclient.yaml~'.` (possibly *with* the quote marks?).

Anyway, it seems like a bit of an edge-case, so I'm going to close it on the assumption that the reporter solved his problem somehow
