### ISSUE TITLE
The trusty/vivid/wily repos need updated python-twisted

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/package-synapse-debian#10]
The trusty/vivid repos only provide python-twisted 15 (and the wily repo does not provide python-twisted, falling back to v. 15 in ubuntu), while synapse requires python-twisted 16, resulting in python-twisted being uninstallable on those systems.

**Comment by richvdh** [comment]
guess this means that nothing since 0.18.7 has worked :/

either way, we've stopped (attempting to) support all of those distros, so I guess it's moot now.
