### ISSUE TITLE
python-matrix-synapse-ldap3 package should depend on python-ldap3 >= 0.9.5

### ISSUE THREAD

**Issue by 14mRh4X0r** [matrix-org/package-synapse-debian#11]
The `LdapAuthProvider` relies on `ldap3` parsing the URI for e.g. port and ldaps, but this was only implemented in version 0.9.5

PS: If I'm in the wrong place for reporting this, please direct me to the right place 😄

**Comment by richvdh** [comment]
python-matrix-synapse-ldap3 is now unmaintained by matrix.org. Either use the matrix-synapse-py3 deb (which includes matrix-synapse-ldap3), or report this to debian (https://packages.debian.org/sid/matrix-synapse-ldap3).
