### ISSUE TITLE
default config is missing uploads_path

### ISSUE THREAD

**Issue by attilakinali** [matrix-org/package-synapse-debian#14]
Hi,

This is basically a copy of https://matrix.org/jira/browse/SYN-585, but it does not seem to be resolved.
The default config in the package is still missing the entry and error's out at startup.

Attila

**Comment by richvdh** [comment]
SYN-585 was:
> @ara4n: default config in matrix-synapse 0.12.0-2 debian pkg is stale
> @ara4n: the lack of upload paths means the pkg just doesn&apos;t run at all out of the box apparently, do setting p1
> @erikjohnston: What distribution was this for? The packages correctly starts on both wheezy and trusty for me (in a schroot).

This appears to have been finally fixed in #28
