### ISSUE TITLE
kill used the wrong way in init script

### ISSUE THREAD

**Issue by attilakinali** [matrix-org/package-synapse-debian#15]
The init script contains a line to kill any old instance of matrix-synapse running:
if [ -r "$PIDFILE" ]; then
                kill -0 `cat $PIDFILE` && return 1
fi

This has two mistakes: 
1) signal 0 does not exist and does nothing if fired off, 

2) if $PIDFILE exists but contains wrong data, it will in best case error out, in the worst case kill an unrelated process. start-stop-daemon already checks whether the same process is running and does nothing in this case.

**Comment by richvdh** [comment]
> signal 0 does not exist and does nothing if fired off,

that's the point. It's just checking if the process is running
