### ISSUE TITLE
merge changes from matrix-synapse package in Debian

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/package-synapse-debian#17]
andrewsh and others forked this repo and have done a bunch of work on it to get matrix-synapse into Debian.  It would probably be good to merge in the changes that they've made that make sense to merge in.

Their repo can be found here: https://anonscm.debian.org/git/collab-maint/matrix-synapse.git

**Comment by andrewshadura** [comment]
Will be addressed by PR #24.

**Comment by richvdh** [comment]
sorry, we're not maintaining this packaging any more.
