### ISSUE TITLE
synapse not restarted on upgrade

### ISSUE THREAD

**Issue by richvdh** [matrix-org/package-synapse-debian#18]
which is ... surprising. It appears to be because of the '--no-start' at https://github.com/matrix-org/package-synapse-debian/blob/debian/debian/rules#L15. 

What's the reasoning here? If it's just to avoid running the server until someone has configured it, we should do that by adding an ENABLED setting to the `default` file, or similar

**Comment by andrewshadura** [comment]
This has been fixed in the [Debian package](https://packages.qa.debian.org/matrix-synapse), which PR #24 will have merged back.

**Comment by erdnaxeli** [comment]
Is it fixed now?

**Comment by richvdh** [comment]
not afaik, no. If anyone could take the time to pull the relevant bits out of the epic #24 PR then that would help.

**Comment by andrewshadura** [comment]
If matrix-org/synapse#1932 ever gets fixed, this repository can be rebased on top of the Debian branch or completely replaced by it, and then the issue will be solved automagically :)

**Comment by richvdh** [comment]
> What's the reasoning here? If it's just to avoid running the server until someone has configured it, we should do that by adding an ENABLED setting to the default file, or similar

https://www.debian.org/doc/debian-policy/ch-opersys.html#managing-the-links has some words on the correct way to do that, fwiw, though it suggests using `init-system-helpers (>= 1.50)`, which is no good because it only landed in buster.

**Comment by maxidor** [comment]
synapse is not started on a fresh install either. synapse is actually never started after the package is deployed.

**Comment by richvdh** [comment]
It may be worth noting that the default configuration of the package *does* enable it in systemd, so it will be started on boot. If anything, that makes the decision to not have it automatically start on installation/upgrade even stranger.

**Comment by richvdh** [comment]
this got fixed in matrix-synapse-py3 (and is fixed in matrix-synapse in downstream debian iirc)
