### ISSUE TITLE
python-lxml as suggestion

### ISSUE THREAD

**Issue by lub** [matrix-org/package-synapse-debian#19]
To use URL previews python-lxml is necessary. I think it would make sense as Suggests.

**Comment by andrewshadura** [comment]
This will be fixed in the latest [Debian package](http://packages.qa.debian.org/matrix-synapse) to be uploaded later today.

**Comment by richvdh** [comment]
this is no longer relevant for matrix-synapse-py3, and as andrew says is fixed downstream in matrix-synapse.
