### ISSUE TITLE
Please drop python-macaroons-nacl and depend on python-pymacaroons >= 0.13 instead

### ISSUE THREAD

**Issue by andrewshadura** [matrix-org/package-synapse-debian#27]
Pymacaroons have switched to nacl recently, so there's no need to ship or depend on python-macaroons-nacl. In fact, providing the package with `Conflicts:` prevents the Debian package for Synapse from being installed:
```
The following packages have unmet dependencies:
 python-pymacaroons-pynacl : Conflicts: python-pymacaroons but 0.13.0-1 is to be installed
```

**Comment by cjwatson** [comment]
In terms of an upgrade path, I'd be happy to add Provides/Conflicts/Replaces for python-pymacaroons-pynacl in the Debian python-pymacaroons package, though I'd only do this if you confirm that python-pymacaroons in fact now meets your needs.

**Comment by richvdh** [comment]
dup of https://github.com/matrix-org/synapse/issues/3164 I think

**Comment by andrewshadura** [comment]
Not a dup since this is an issue with the packaging, and the other issue is with Synapse itself. These are two independent issues.

**Comment by richvdh** [comment]
The debian packaging just depends on the versions which synapse requires. I'm missing how they are separate issues?

**Comment by andrewshadura** [comment]
Because packaging and upstream development are two different processes?

**Comment by richvdh** [comment]
except in this case they aren't.
