### ISSUE TITLE
server_name.yaml creation 

### ISSUE THREAD

**Issue by PaulFreund** [matrix-org/package-synapse-debian#4]
Upon upgrade to 0.18.3 the file server_name.yaml has been crated with an auto assumed hostname. This was not the hostname for my matrix-synapse instance and thus the server did not start and threw errors in syslog for server_name mismatch with the hostname in database.

**Comment by richvdh** [comment]
sadly I don't think we're ever going to know why this happened, once upon a time.

**Comment by richvdh** [comment]
(though it's probably actually a dup of #21)
