### ISSUE TITLE
Use Postgres by default

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/package-synapse-debian#40]
In preparation for https://github.com/matrix-org/synapse/issues/2917, the Debian package should use Postgres by default or add an option to use Postgres during installation https://github.com/matrix-org/synapse/issues/2317

Related https://github.com/matrix-org/synapse/issues/4270

**Comment by richvdh** [comment]
we're not maintaining the matrix-synapse packaging any more, so I'm going to close this in favour of matrix-org/synapse#2317 and matrix-org/synapse#4270.
