### ISSUE TITLE
ModuleNotFoundError: No module named 'synapse'

### ISSUE THREAD

**Issue by Zjemm** [matrix-org/package-synapse-debian#43]
i wanted to upgrade to the python3 version of matrix, but it failed. 
So i thought i create a new empty debian (buster) container and do a fresh install to see if that works.

installed only the following: apt install matrix-synapse-py3

but i get:
/opt/venvs/matrix-synapse/bin/python: Error while finding module specification for 'synapse.app.homeserver' (ModuleNotFoundError: No module named 'synapse')

on starting.

could it be that there is some missing module in the debian package?

**Comment by Zjemm** [comment]
solved with some help on matrix. when upgrading to a newer debian version (buster) forgot to change the repo url in apt

**Comment by richvdh** [comment]
see also https://github.com/matrix-org/synapse/issues/4431
