### ISSUE TITLE
Jessie package doesn't install python-cffi (of the correct version)

### ISSUE THREAD

**Issue by SohumB** [matrix-org/package-synapse-debian#8]
On a fresh jessie system, `python-cffi-backend = 1.4.2-2~bpo8+1` as provided by the repository says it breaks `python-cffi < 1`, which is the only version available on jessie, so synapse gets installed with (eventually) `python-cryptography = 0.6.1-1` instead of `python-cryptography = 1.3.4-1~bpo8+2` as a dependency. This means it never starts:

```
Feb 15 18:14:56 tars python[10355]: from twisted.conch.ssh import address, keys, _kex
Feb 15 18:14:56 tars python[10355]: File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/keys.py", line 25, in <module>
Feb 15 18:14:56 tars python[10355]: from cryptography.hazmat.primitives.asymmetric.utils import (
Feb 15 18:14:56 tars python[10355]: ImportError: No module named utils
```

**Comment by balert** [comment]
same here, looks like package dependencies are broken.

**Comment by uhoreg** [comment]
As a workaround until the matrix.org repo is fixed, you can install the correct version of python-cffi from backports.debian.org.

**Comment by balert** [comment]
Works for me, thanks for the help.

**Comment by uhoreg** [comment]
It looks like python-cffi has been added to the repo, so this issue can be closed
